name: Print Secret Env Variable

on: 
    push:
        branches: [ "feature/*"]
jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret
        env:
          MY_SECRET: ${{ secrets.AWS_ACCESS_KEY_ID }}
          MY_SEC2: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            echo "$MY_SECRET"
            echo "$MY_SEC2"

