name: Print Secret Env Variable

on:
  push:
    branches:
      - "feature/*"

jobs:
  print-secret:
    runs-on: ubuntu-latest

    env:   # 👈 move env to job level so all steps can use it
      MY_SECRET: ${{ secrets.AWS_ACCESS_KEY_ID }}
      MY_SEC2: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Print secret
        run: |
          echo "$MY_SECRET"
          echo "$MY_SEC2"

      - name: Check secret presence
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "MY_SECRET is empty"
          else
            echo "MY_SECRET is set"
          fi